"""Published CDX numeric schema. Regenerate with scripts/regenerate_cdx_schema.py.
Source: https://bobhanson.github.io/IUPAC-FAIRSpec/cdx_sdk/TableOfProperties.htm
"""

PROPERTIES = {
    0x0001: ("CreationUserName", "CDXString", {}),
    0x0002: ("CreationDate", "CDXDate", {}),
    0x0003: ("CreationProgram", "CDXString", {}),
    0x0004: ("ModificationUserName", "CDXString", {}),
    0x0005: ("ModificationDate", "CDXDate", {}),
    0x0006: ("ModificationProgram", "CDXString", {}),
    0x0008: ("Name", "CDXString", {}),
    0x0009: ("Comment", "CDXString", {}),
    0x000A: ("Z", "INT16", {}),
    0x000B: ("RegistryNumber", "CDXString", {}),
    0x000C: ("RegistryAuthority", "CDXString", {}),
    0x000E: ("RepresentsProperty", "CDXRepresentsProperty", {}),
    0x000F: ("IgnoreWarnings", "CDXBooleanImplied", {}),
    0x0010: ("Warning", "CDXString", {}),
    0x0011: ("Visible", "CDXBoolean", {}),
    0x0012: ("SupersededBy", "CDXObjectID", {}),
    0x0100: ("fonttable", "CDXFontTable", {}),
    0x0200: ("p", "CDXPoint2D", {}),
    0x0201: ("xyz", "CDXPoint3D", {}),
    0x0202: ("extent", "CDXPoint2D", {}),
    0x0203: ("extent3D", "CDXPoint3D", {}),
    0x0204: ("BoundingBox", "CDXRectangle", {}),
    0x0205: ("RotationAngle", "INT32", {}),
    0x0206: ("BoundsInParent", "CDXRectangle", {}),
    0x0207: ("Head3D", "CDXPoint3D", {}),
    0x0208: ("Tail3D", "CDXPoint3D", {}),
    0x0209: ("TopLeft", "CDXPoint2D", {}),
    0x020A: ("TopRight", "CDXPoint2D", {}),
    0x020B: ("BottomRight", "CDXPoint2D", {}),
    0x020C: ("BottomLeft", "CDXPoint2D", {}),
    0x020D: ("Center3D", "CDXPoint3D", {}),
    0x020E: ("MajorAxisEnd3D", "CDXPoint3D", {}),
    0x020F: ("MinorAxisEnd3D", "CDXPoint3D", {}),
    0x0300: ("colortable", "CDXColorTable", {}),
    0x0301: ("color", "UINT16", {}),
    0x0302: ("bgcolor", "INT16", {}),
    0x0400: (
        "NodeType",
        "INT16",
        {
            "Unspecified": 0,
            "Element": 1,
            "ElementList": 2,
            "ElementListNickname": 3,
            "Nickname": 4,
            "Fragment": 5,
            "Formula": 6,
            "GenericNickname": 7,
            "AnonymousAlternativeGroup": 8,
            "NamedAlternativeGroup": 9,
            "MultiAttachment": 10,
            "VariableAttachment": 11,
            "ExternalConnectionPoint": 12,
            "LinkNode": 13,
        },
    ),
    0x0401: (
        "LabelDisplay",
        "INT8",
        {"Auto": 0, "Left": 1, "Center": 2, "Right": 3, "Above": 4, "Below": 5},
    ),
    0x0402: ("Element", "INT16", {}),
    0x0403: ("ElementList", "CDXElementList", {}),
    0x0404: ("Formula", "CDXFormula", {}),
    0x0420: ("Isotope", "INT16", {}),
    0x0421: ("Charge", "INT8", {}),
    0x0422: ("Radical", "UINT8", {"None": 0, "Singlet": 1, "Doublet": 2, "Triplet": 3}),
    0x0423: ("FreeSites", "UINT8", {}),
    0x0424: ("ImplicitHydrogens", "CDXBooleanImplied", {}),
    0x0425: (
        "RingBondCount",
        "INT8",
        {
            "Unspecified": -1,
            "NoRingBonds": 0,
            "AsDrawn": 1,
            "SimpleRing": 2,
            "Fusion": 3,
            "SpiroOrHigher": 4,
        },
    ),
    0x0426: ("UnsaturatedBonds", "INT8", {"Unspecified": 0, "MustBeAbsent": 1, "MustBePresent": 2}),
    0x0427: ("RxnChange", "CDXBooleanImplied", {}),
    0x0428: ("RxnStereo", "INT8", {"Unspecified": 0, "Inversion": 1, "Retention": 2}),
    0x0429: ("AbnormalValence", "CDXBooleanImplied", {}),
    0x042B: ("NumHydrogens", "UINT16", {}),
    0x042E: ("HDot", "CDXBooleanImplied", {}),
    0x042F: ("HDash", "CDXBooleanImplied", {}),
    0x0430: (
        "Geometry",
        "INT8",
        {
            "Unknown": 0,
            "1": 1,
            "Linear": 2,
            "Bent": 3,
            "TrigonalPlanar": 4,
            "TrigonalPyramidal": 5,
            "SquarePlanar": 6,
            "Tetrahedral": 7,
            "TrigonalBipyramidal": 8,
            "SquarePyramidal": 9,
            "5": 10,
            "Octahedral": 11,
            "6": 12,
            "7": 13,
            "8": 14,
            "9": 15,
            "10": 16,
        },
    ),
    0x0431: ("BondOrdering", "CDXObjectIDArray", {}),
    0x0432: ("Attachments", "CDXObjectIDArrayWithCounts", {}),
    0x0433: ("GenericNickname", "CDXString", {}),
    0x0434: ("AltGroupID", "CDXObjectID", {}),
    0x0435: ("SubstituentsUpTo", "UINT8", {}),
    0x0436: ("SubstituentsExactly", "UINT8", {}),
    0x0437: ("AS", "INT8", {"U": 0, "N": 1, "R": 2, "S": 3, "r": 4, "s": 5, "u": 6}),
    0x0438: ("Translation", "INT8", {"Equal": 0, "Broad": 1, "Narrow": 2, "Any": 3}),
    0x0439: ("AtomNumber", "CDXString", {}),
    0x043A: ("ShowAtomQuery", "CDXBoolean", {}),
    0x043B: ("ShowAtomStereo", "CDXBoolean", {}),
    0x043C: ("ShowAtomNumber", "CDXBoolean", {}),
    0x043D: ("LinkCountLow", "INT16", {}),
    0x043E: ("LinkCountHigh", "INT16", {}),
    0x043F: (
        "IsotopicAbundance",
        "INT8",
        {"Unspecified": 0, "Any": 1, "Natural": 2, "Enriched": 3, "Deficient": 4, "Nonnatural": 5},
    ),
    0x0440: (
        "ExternalConnectionType",
        "INT8",
        {"Unspecified": 0, "Diamond": 1, "Star": 2, "PolymerBead": 3, "Wavy": 4},
    ),
    0x0441: ("GenericList", "CDXGenericList", {}),
    0x0442: ("ShowTerminalCarbonLabels", "CDXBooleanImplied", {}),
    0x0443: ("ShowNonTerminalCarbonLabels", "CDXBooleanImplied", {}),
    0x0444: ("HideImplicitHydrogens", "CDXBooleanImplied", {}),
    0x0445: ("ShowAtomEnhancedStereo", "CDXBoolean", {}),
    0x0446: (
        "EnhancedStereoType",
        "UINT8",
        {"Unspecified": 0, "None": 1, "Absolute": 2, "Or": 3, "And": 4},
    ),
    0x0447: ("EnhancedStereoGroupNum", "UINT16", {}),
    0x0500: ("Racemic", "CDXBoolean", {}),
    0x0501: ("Absolute", "CDXBoolean", {}),
    0x0502: ("Relative", "CDXBoolean", {}),
    0x0503: ("Formula", "CDXFormula", {}),
    0x0504: ("Weight", "FLOAT64", {}),
    0x0505: ("ConnectionOrder", "CDXObjectIDArray", {}),
    0x0600: (
        "Order",
        "INT16",
        {
            "1": 1,
            "2": 2,
            "3": 4,
            "4": 8,
            "5": 16,
            "6": 32,
            "0.5": 64,
            "1.5": 128,
            "2.5": 256,
            "3.5": 512,
            "4.5": 1024,
            "5.5": 2048,
            "dative": 4096,
            "ionic": 8192,
            "hydrogen": 16384,
            "threecenter": 32768,
        },
    ),
    0x0601: (
        "Display",
        "INT16",
        {
            "Solid": 0,
            "Dash": 1,
            "Hash": 2,
            "WedgedHashBegin": 3,
            "WedgedHashEnd": 4,
            "Bold": 5,
            "WedgeBegin": 6,
            "WedgeEnd": 7,
            "Wavy": 8,
            "HollowWedgeBegin": 9,
            "HollowWedgeEnd": 10,
            "WavyWedgeBegin": 11,
            "WavyWedgeEnd": 12,
            "Dot": 13,
            "DashDot": 14,
        },
    ),
    0x0602: (
        "Display2",
        "INT16",
        {
            "Solid": 0,
            "Dash": 1,
            "Hash": 2,
            "WedgedHashBegin": 3,
            "WedgedHashEnd": 4,
            "Bold": 5,
            "WedgeBegin": 6,
            "WedgeEnd": 7,
            "Wavy": 8,
            "HollowWedgeBegin": 9,
            "HollowWedgeEnd": 10,
            "WavyWedgeBegin": 11,
            "WavyWedgeEnd": 12,
            "Dot": 13,
            "DashDot": 14,
        },
    ),
    0x0603: ("DoublePosition", "INT16", {"Center": 256, "Right": 257, "Left": 258}),
    0x0604: ("B", "CDXObjectID", {}),
    0x0605: ("E", "CDXObjectID", {}),
    0x0606: ("Topology", "INT8", {"Unspecified": 0, "Ring": 1, "Chain": 2, "RingOrChain": 3}),
    0x0607: (
        "RxnParticipation",
        "INT8",
        {
            "Unspecified": 0,
            "ReactionCenter": 1,
            "MakeOrBreak": 2,
            "ChangeType": 3,
            "MakeAndChange": 4,
            "NotReactionCenter": 5,
            "NoChange": 6,
            "Unmapped": 7,
        },
    ),
    0x0608: ("BeginAttach", "UINT8", {}),
    0x0609: ("EndAttach", "UINT8", {}),
    0x060A: ("BS", "INT8", {"U": 0, "N": 1, "E": 2, "Z": 3}),
    0x060B: ("BondCircularOrdering", "CDXObjectIDArray", {}),
    0x060C: ("ShowBondQuery", "CDXBoolean", {}),
    0x060D: ("ShowBondStereo", "CDXBoolean", {}),
    0x060E: ("CrossingBonds", "CDXObjectIDArray", {}),
    0x060F: ("ShowBondRxn", "CDXBoolean", {}),
    0x0700: ("temp_Text", "CDXString", {}),
    0x0701: (
        "Justification",
        "INT8",
        {
            "Right": -1,
            "Left": 0,
            "Center": 1,
            "Full": 2,
            "Above": 3,
            "Below": 4,
            "Auto": 5,
            "Best": 6,
        },
    ),
    0x0702: ("LineHeight", "UINT16", {}),
    0x0703: ("WordWrapWidth", "INT16", {}),
    0x0704: ("LineStarts", "INT16ListWithCounts", {}),
    0x0705: (
        "LabelAlignment",
        "INT8",
        {"Auto": 0, "Left": 1, "Center": 2, "Right": 3, "Above": 4, "Below": 5, "Best": 6},
    ),
    0x0706: ("LabelLineHeight", "INT16", {}),
    0x0707: ("CaptionLineHeight", "INT16", {}),
    0x0708: ("InterpretChemically", "CDXBooleanImplied", {}),
    0x0709: ("UTF8Text", "CDXString", {}),
    0x0800: ("MacPrintInfo", "Unformatted", {}),
    0x0801: ("WinPrintInfo", "Unformatted", {}),
    0x0802: ("PrintMargins", "CDXRectangle", {}),
    0x0803: ("ChainAngle", "INT32", {}),
    0x0804: ("BondSpacing", "INT16", {}),
    0x0805: ("BondLength", "CDXCoordinate", {}),
    0x0806: ("BoldWidth", "CDXCoordinate", {}),
    0x0807: ("LineWidth", "CDXCoordinate", {}),
    0x0808: ("MarginWidth", "CDXCoordinate", {}),
    0x0809: ("HashSpacing", "CDXCoordinate", {}),
    0x080A: ("temp_LabelStyle", "CDXFontStyle", {}),
    0x080B: ("temp_CaptionStyle", "CDXFontStyle", {}),
    0x080C: (
        "CaptionJustification",
        "INT8",
        {
            "Right": -1,
            "Left": 0,
            "Center": 1,
            "Full": 2,
            "Above": 3,
            "Below": 4,
            "Auto": 5,
            "Best": 6,
        },
    ),
    0x080D: ("FractionalWidths", "CDXBooleanImplied", {}),
    0x080E: ("Magnification", "INT16", {}),
    0x080F: ("WidthPages", "INT16", {}),
    0x0810: ("HeightPages", "INT16", {}),
    0x0811: ("DrawingSpace", "INT8", {"Pages": 0, "Poster": 1}),
    0x0812: ("Width", "CDXCoordinate", {}),
    0x0813: ("Height", "CDXCoordinate", {}),
    0x0814: ("PageOverlap", "CDXCoordinate", {}),
    0x0815: ("Header", "CDXString", {}),
    0x0816: ("HeaderPosition", "CDXCoordinate", {}),
    0x0817: ("Footer", "CDXString", {}),
    0x0818: ("FooterPosition", "CDXCoordinate", {}),
    0x0819: ("PrintTrimMarks", "CDXBooleanImplied", {}),
    0x081A: ("LabelFont", "INT16", {}),
    0x081B: ("CaptionFont", "INT16", {}),
    0x081C: ("LabelSize", "INT16", {}),
    0x081D: ("CaptionSize", "INT16", {}),
    0x081E: ("LabelFace", "INT16", {}),
    0x081F: ("CaptionFace", "INT16", {}),
    0x0820: ("LabelColor", "INT16", {}),
    0x0821: ("CaptionColor", "INT16", {}),
    0x0822: ("BondSpacingAbs", "CDXCoordinate", {}),
    0x0823: (
        "LabelJustification",
        "INT8",
        {
            "Right": -1,
            "Left": 0,
            "Center": 1,
            "Full": 2,
            "Above": 3,
            "Below": 4,
            "Auto": 5,
            "Best": 6,
        },
    ),
    0x0824: ("FixInPlaceExtent", "CDXPoint2D", {}),
    0x0825: ("Side", "UINT16", {"undefined": 0, "top": 1, "left": 2, "bottom": 3, "right": 4}),
    0x0826: ("FixInPlaceGap", "CDXPoint2D", {}),
    0x0827: ("CartridgeData", "Unformatted", {}),
    0x0900: ("WindowIsZoomed", "CDXBooleanImplied", {}),
    0x0901: ("WindowPosition", "CDXPoint2D", {}),
    0x0902: ("WindowSize", "CDXPoint2D", {}),
    0x0A00: (
        "GraphicType",
        "INT16",
        {
            "Undefined": 0,
            "Line": 1,
            "Arc": 2,
            "Rectangle": 3,
            "Oval": 4,
            "Orbital": 5,
            "Bracket": 6,
            "Symbol": 7,
        },
    ),
    0x0A01: ("LineType", "INT16", {"Solid": 0, "Dashed": 1, "Bold": 2, "Wavy": 4}),
    0x0A02: (
        "ArrowType",
        "INT16",
        {
            "NoHead": 0,
            "HalfHead": 1,
            "FullHead": 2,
            "Resonance": 4,
            "Equilibrium": 8,
            "Hollow": 16,
            "RetroSynthetic": 32,
            "NoGo": 64,
            "Dipole": 128,
        },
    ),
    0x0A03: (
        "RectangleType",
        "INT16",
        {
            "Plain": 0,
            "RoundEdge": 1,
            "Shadow": 2,
            "Shaded": 4,
            "Filled": 8,
            "Dashed": 16,
            "Bold": 32,
        },
    ),
    0x0A04: (
        "OvalType",
        "INT16",
        {"Circle": 1, "Shaded": 2, "Filled": 4, "Dashed": 8, "Bold": 16, "Shadowed": 32},
    ),
    0x0A05: (
        "OrbitalType",
        "INT16",
        {
            "s": 0,
            "oval": 1,
            "lobe": 2,
            "p": 3,
            "hybridPlus": 4,
            "hybridMinus": 5,
            "dz2Plus": 6,
            "dz2Minus": 7,
            "dxy": 8,
            "sShaded": 256,
            "ovalShaded": 257,
            "lobeShaded": 258,
            "pShaded": 259,
            "sFilled": 512,
            "ovalFilled": 513,
            "lobeFilled": 514,
            "pFilled": 515,
            "hybridPlusFilled": 516,
            "hybridMinusFilled": 517,
            "dz2PlusFilled": 518,
            "dz2MinusFilled": 519,
            "dxyFilled": 520,
        },
    ),
    0x0A06: (
        "BracketType",
        "INT16",
        {"RoundPair": 0, "SquarePair": 1, "CurlyPair": 2, "Square": 3, "Curly": 4, "Round": 5},
    ),
    0x0A07: (
        "SymbolType",
        "INT16",
        {
            "LonePair": 13,
            "Electron": 1,
            "RadicalCation": 2,
            "RadicalAnion": 3,
            "CirclePlus": 4,
            "CircleMinus": 5,
            "Dagger": 6,
            "DoubleDagger": 7,
            "Plus": 8,
            "Minus": 9,
            "Racemic": 10,
            "Absolute": 11,
            "Relative": 12,
        },
    ),
    0x0A08: (
        "CurveType",
        "INT16",
        {
            "1": 1,
            "2": 2,
            "4": 4,
            "8": 8,
            "16": 16,
            "32": 32,
            "64": 64,
            "128": 128,
            "256": 256,
            "512": 512,
            "0": 0,
        },
    ),
    0x0A20: ("HeadSize", "INT16", {}),
    0x0A21: ("AngularSize", "INT16", {}),
    0x0A22: ("LipSize", "INT16", {}),
    0x0A23: ("CurvePoints", "CDXCurvePoints", {}),
    0x0A24: (
        "BracketUsage",
        "INT8",
        {
            "Unspecified": 0,
            "Unused1": 1,
            "Unused2": 2,
            "SRU": 3,
            "Monomer": 4,
            "Mer": 5,
            "Copolymer": 6,
            "CopolymerAlternating": 7,
            "CopolymerRandom": 8,
            "CopolymerBlock": 9,
            "Crosslink": 10,
            "Graft": 11,
            "Modification": 12,
            "Component": 13,
            "MixtureUnordered": 14,
            "MixtureOrdered": 15,
            "MultipleGroup": 16,
            "Generic": 17,
            "Anypolymer": 18,
        },
    ),
    0x0A25: (
        "PolymerRepeatPattern",
        "INT8",
        {"HeadToTail": 0, "HeadToHead": 1, "EitherUnknown": 2},
    ),
    0x0A26: ("PolymerFlipType", "INT8", {"Unspecified": 0, "NoFlip": 1, "Flip": 2}),
    0x0A27: ("BracketedObjectIDs", "CDXObjectIDArray", {}),
    0x0A28: ("RepeatCount", "FLOAT64", {}),
    0x0A29: ("ComponentOrder", "INT16", {}),
    0x0A2A: ("SRULabel", "CDXString", {}),
    0x0A2B: ("GraphicID", "CDXObjectID", {}),
    0x0A2C: ("BondID", "CDXObjectID", {}),
    0x0A2D: ("InnerAtomID", "CDXObjectID", {}),
    0x0A2E: ("CurvePoints3D", "CDXCurvePoints3D", {}),
    0x0A2F: ("ArrowheadType", "INT16", {}),
    0x0A30: ("ArrowheadCenterSize", "UINT16", {}),
    0x0A31: ("ArrowheadWidth", "UINT16", {}),
    0x0A32: ("ShadowSize", "UINT16", {}),
    0x0A33: ("ArrowShaftSpacing", "UINT16", {}),
    0x0A34: ("ArrowEquilibriumRatio", "UINT16", {}),
    0x0A35: ("ArrowheadHead", "INT16", {}),
    0x0A36: ("ArrowheadTail", "INT16", {}),
    0x0A37: ("FillType", "INT16", {}),
    0x0A38: ("Closed", "CDXBoolean", {}),
    0x0A3A: ("Dipole", "CDXBoolean", {}),
    0x0A3B: ("NoGo", "INT8", {}),
    0x0A3C: ("CornerRadius", "INT16", {}),
    0x0A3D: ("FrameType", "INT16", {}),
    0x0A60: ("Edition", "Unformatted", {}),
    0x0A61: ("EditionAlias", "Unformatted", {}),
    0x0A62: ("MacPICT", "Unformatted", {}),
    0x0A63: ("WindowsMetafile", "Unformatted", {}),
    0x0A64: ("OLEObject", "Unformatted", {}),
    0x0A65: ("EnhancedMetafile", "Unformatted", {}),
    0x0A6E: ("GIF", "Unformatted", {}),
    0x0A6F: ("TIFF", "Unformatted", {}),
    0x0A70: ("PNG", "Unformatted", {}),
    0x0A71: ("JPEG", "Unformatted", {}),
    0x0A72: ("BMP", "Unformatted", {}),
    0x0A80: ("XSpacing", "FLOAT64", {}),
    0x0A81: ("XLow", "FLOAT64", {}),
    0x0A82: (
        "XType",
        "INT16",
        {
            "Unknown": 0,
            "Wavenumbers": 1,
            "Microns": 2,
            "Hertz": 3,
            "MassUnits": 4,
            "PartsPerMillion": 5,
            "Other": 6,
        },
    ),
    0x0A83: (
        "YType",
        "INT16",
        {
            "Unknown": 0,
            "Absorbance": 1,
            "Transmittance": 2,
            "PercentTransmittance": 3,
            "Other": 4,
            "ArbitraryUnits": 5,
        },
    ),
    0x0A84: ("XAxisLabel", "CDXString", {}),
    0x0A85: ("YAxisLabel", "CDXString", {}),
    0x0A86: ("temp_SpectrumDataPoint", "FLOAT64", {}),
    0x0A87: (
        "Class",
        "INT16",
        {
            "Unknown": 0,
            "Chromatogram": 1,
            "Infrared": 2,
            "UVVis": 3,
            "XRayDiffraction": 4,
            "MassSpectrum": 5,
            "NMR": 6,
            "Raman": 7,
            "Fluorescence": 8,
            "Atomic": 9,
        },
    ),
    0x0A88: ("YLow", "FLOAT64", {}),
    0x0A89: ("YScale", "FLOAT64", {}),
    0x0AA0: ("OriginFraction", "FLOAT64", {}),
    0x0AA1: ("SolventFrontFraction", "FLOAT64", {}),
    0x0AA2: ("ShowOrigin", "CDXBoolean", {}),
    0x0AA3: ("ShowSolventFront", "CDXBoolean", {}),
    0x0AA4: ("ShowBorders", "CDXBoolean", {}),
    0x0AA5: ("ShowSideTicks", "CDXBoolean", {}),
    0x0AB0: ("Rf", "FLOAT64", {}),
    0x0AB1: ("Tail", "CDXCoordinate", {}),
    0x0AB2: ("ShowRf", "CDXBoolean", {}),
    0x0B00: ("TextFrame", "CDXRectangle", {}),
    0x0B01: ("GroupFrame", "CDXRectangle", {}),
    0x0B02: ("Valence", "INT16", {}),
    0x0B80: (
        "GeometricFeature",
        "INT8",
        {
            "Undefined": 0,
            "PointFromPointPointDistance": 1,
            "PointFromPointPointPercentage": 2,
            "PointFromPointNormalDistance": 3,
            "LineFromPoints": 4,
            "PlaneFromPoints": 5,
            "PlaneFromPointLine": 6,
            "CentroidFromPoints": 7,
            "NormalFromPointPlane": 8,
        },
    ),
    0x0B81: ("RelationValue", "FLOAT64", {}),
    0x0B82: ("BasisObjects", "CDXObjectIDArray", {}),
    0x0B83: (
        "ConstraintType",
        "INT8",
        {"Undefined": 0, "Distance": 1, "Angle": 2, "ExclusionSphere": 3},
    ),
    0x0B84: ("ConstraintMin", "FLOAT64", {}),
    0x0B85: ("ConstraintMax", "FLOAT64", {}),
    0x0B86: ("IgnoreUnconnectedAtoms", "CDXBooleanImplied", {}),
    0x0B87: ("DihedralIsChiral", "CDXBooleanImplied", {}),
    0x0B88: ("PointIsDirected", "CDXBooleanImplied", {}),
    0x0BB0: ("ChemicalPropertyType", "UINT32", {"Unspecified": 0, "ChemicalName": 1}),
    0x0BB1: ("ChemicalPropertyDisplayID", "CDXObjectID", {}),
    0x0BB2: ("ChemicalPropertyIsActive", "CDXBoolean", {}),
    0x0C00: ("ReactionStepAtomMap", "CDXObjectIDArray", {}),
    0x0C01: ("ReactionStepReactants", "CDXObjectIDArray", {}),
    0x0C02: ("ReactionStepProducts", "CDXObjectIDArray", {}),
    0x0C03: ("ReactionStepPlusses", "CDXObjectIDArray", {}),
    0x0C04: ("ReactionStepArrows", "CDXObjectIDArray", {}),
    0x0C05: ("ReactionStepObjectsAboveArrow", "CDXObjectIDArray", {}),
    0x0C06: ("ReactionStepObjectsBelowArrow", "CDXObjectIDArray", {}),
    0x0C07: ("ReactionStepAtomMapManual", "CDXObjectIDArray", {}),
    0x0C08: ("ReactionStepAtomMapAuto", "CDXObjectIDArray", {}),
    0x0D00: ("TagType", "INT16", {"Unknown": 0, "Double": 1, "Long": 2, "String": 3}),
    0x0D03: ("Tracking", "CDXBoolean", {}),
    0x0D04: ("Persistent", "CDXBoolean", {}),
    0x0D05: ("Value", "varies", {}),
    0x0D06: ("PositioningType", "INT8", {"auto": 0, "angle": 1, "offset": 2, "absolute": 3}),
    0x0D07: ("PositioningAngle", "INT32", {}),
    0x0D08: ("PositioningOffset", "CDXPoint2D", {}),
    0x0E00: ("SequenceIdentifier", "CDXString", {}),
    0x0F00: ("CrossReferenceContainer", "CDXString", {}),
    0x0F01: ("CrossReferenceDocument", "CDXString", {}),
    0x0F02: ("CrossReferenceIdentifier", "CDXString", {}),
    0x0F03: ("CrossReferenceSequence", "CDXString", {}),
    0x1000: ("PaneHeight", "CDXCoordinate", {}),
    0x1001: ("NumRows", "INT16", {}),
    0x1002: ("NumColumns", "INT16", {}),
    0x1100: ("Integral", "CDXBoolean", {}),
    0x1FF0: ("SplitterPositions", "CDXObjectIDArray", {}),
    0x1FF1: (
        "PageDefinition",
        "INT8",
        {
            "Undefined": 0,
            "Center": 1,
            "TL4": 2,
            "IDTerm": 3,
            "FlushLeft": 4,
            "FlushRight": 5,
            "Reaction1": 6,
            "Reaction2": 7,
            "MulticolumnTL4": 8,
            "MulticolumnNonTL4": 9,
            "UserDefined": 10,
        },
    ),
}
