# Original controlled test drawing, MIT OR Apache-2.0, not experimental NMR data.
# Runs headlessly; does not launch an application or change Office documents.
param(
    [Parameter(Mandatory=$true)][string]$Output,
    [single]$OriginX = 0,
    [single]$OriginY = 0,
    [string]$Stem = 'controlled-spectrum'
)
$ErrorActionPreference = 'Stop'
Add-Type -AssemblyName System.Drawing
[IO.Directory]::CreateDirectory($Output) | Out-Null
$path = Join-Path $Output ($Stem + '.emf')
$reference = [Drawing.Graphics]::FromHwnd([IntPtr]::Zero)
$dc = $reference.GetHdc()
try {
    $frame = [Drawing.RectangleF]::new($OriginX, $OriginY, 100, 60)
    $metafile = [Drawing.Imaging.Metafile]::new($path, $dc, $frame,
        [Drawing.Imaging.MetafileFrameUnit]::Millimeter,
        [Drawing.Imaging.EmfType]::EmfPlusDual)
} finally {
    $reference.ReleaseHdc($dc)
    $reference.Dispose()
}
$g = [Drawing.Graphics]::FromImage($metafile)
$pen = [Drawing.Pen]::new([Drawing.Color]::Black, 0.16)
$blue = [Drawing.Pen]::new([Drawing.Color]::FromArgb(20, 80, 180), 0.22)
$font = [Drawing.Font]::new('Arial', 8)
$small = [Drawing.Font]::new('Arial', 6)
$inset = [Drawing.Bitmap]::new(8, 4)
try {
    $g.PageUnit = [Drawing.GraphicsUnit]::Millimeter
    if ($OriginX -ne 0 -or $OriginY -ne 0) {
        $g.TranslateTransform($OriginX, $OriginY)
    }
    $g.SmoothingMode = [Drawing.Drawing2D.SmoothingMode]::AntiAlias
    $g.Clear([Drawing.Color]::White)
    $g.DrawString('Controlled 1H NMR-like spectrum', $font, [Drawing.Brushes]::Black, 5, 3)
    $g.DrawString('Original fixture; not experimental data', $small, [Drawing.Brushes]::Black, 5, 8)
    $g.DrawLine($pen, 8, 47, 94, 47)
    $g.DrawLine($pen, 8, 15, 8, 47)
    for ($tick = 0; $tick -le 12; $tick++) {
        $x = 8 + $tick * 86 / 12
        $g.DrawLine($pen, $x, 47, $x, 48)
        $g.DrawString([string](12 - $tick), $small, [Drawing.Brushes]::Black, $x - 1, 49)
    }
    $g.DrawString('Chemical shift / ppm', $small, [Drawing.Brushes]::Black, 38, 55)
    $peaks = @(@(20, 22), @(35, 14), @(37, 17), @(39, 14), @(64, 28), @(66, 33), @(68, 28), @(86, 10))
    foreach ($peak in $peaks) {
        $x = [single]$peak[0]; $height = [single]$peak[1]
        $points = [Drawing.PointF[]]@(
            [Drawing.PointF]::new($x - 1, 47),
            [Drawing.PointF]::new($x - 0.18, 47 - $height * 0.20),
            [Drawing.PointF]::new($x, 47 - $height),
            [Drawing.PointF]::new($x + 0.18, 47 - $height * 0.20),
            [Drawing.PointF]::new($x + 1, 47))
        $g.DrawLines($blue, $points)
    }
    # A small raster inset exercises mixed content without rasterizing the plot.
    for ($y = 0; $y -lt 4; $y++) {
        for ($x = 0; $x -lt 8; $x++) {
            $color = if ($x -lt 4) { [Drawing.Color]::Red } else { [Drawing.Color]::LimeGreen }
            $inset.SetPixel($x, $y, $color)
        }
    }
    $g.DrawImage($inset, [Drawing.RectangleF]::new(77, 4, 16, 6))
} finally {
    $g.Dispose(); $metafile.Dispose(); $pen.Dispose(); $blue.Dispose()
    $font.Dispose(); $small.Dispose(); $inset.Dispose()
}
$bytes = [IO.File]::ReadAllBytes($path)
$nativeFrame = @(
    [BitConverter]::ToInt32($bytes,24), [BitConverter]::ToInt32($bytes,28),
    [BitConverter]::ToInt32($bytes,32), [BitConverter]::ToInt32($bytes,36))
# Preserve the untouched native recording as well. Author the controlled
# fixture's physical Frame explicitly in MS-EMF's 0.01 mm units, since GDI+
# rounds this constructor through desktop pixels. Drawing records stay exact.
[IO.File]::WriteAllBytes((Join-Path $Output ($Stem + '-native.emf')), $bytes)
$left = [int][Math]::Round($OriginX * 100)
$top = [int][Math]::Round($OriginY * 100)
[BitConverter]::GetBytes($left).CopyTo($bytes,24)
[BitConverter]::GetBytes($top).CopyTo($bytes,28)
[BitConverter]::GetBytes([int]($left + 10000)).CopyTo($bytes,32)
[BitConverter]::GetBytes([int]($top + 6000)).CopyTo($bytes,36)
[IO.File]::WriteAllBytes($path, $bytes)
$read = [Drawing.Imaging.Metafile]::new($path)
try {
    $header = $read.GetMetafileHeader()
    [ordered]@{
        source = 'Original controlled data, generated by generate_spectrum.ps1'
        license = 'MIT OR Apache-2.0'
        sha256 = (Get-FileHash $path -Algorithm SHA256).Hash.ToLower()
        bytes = $bytes.Length
        frameHundredthMillimeter = @(
            [BitConverter]::ToInt32($bytes,24), [BitConverter]::ToInt32($bytes,28),
            [BitConverter]::ToInt32($bytes,32), [BitConverter]::ToInt32($bytes,36))
        expectedWidthMm = 100
        expectedHeightMm = 60
        nativeConstructorFrameHundredthMillimeter = $nativeFrame
        authoredPhysicalFrame = 'Frame explicitly set to the requested origin and 100x60 mm extent; drawing records unchanged'
        originMillimeter = @($OriginX, $OriginY)
        metafileType = [string]$header.Type
        dpiX = $header.DpiX
        dpiY = $header.DpiY
        systemDrawingAssembly = [Drawing.Graphics].Assembly.FullName
    } | ConvertTo-Json -Depth 4 | Set-Content (Join-Path $Output ($Stem + '.source.json')) -Encoding UTF8
} finally { $read.Dispose() }
