// Pinned upstream XML resources, embedded without file-system overrides.
pub(crate) const XML_RESOURCES: &[(&str, &str)] = &[
    ("alkanes.xml", include_str!("../resources/xml/alkanes.xml")),
    (
        "aminoAcids.xml",
        include_str!("../resources/xml/aminoAcids.xml"),
    ),
    (
        "arylGroups.xml",
        include_str!("../resources/xml/arylGroups.xml"),
    ),
    (
        "arylSubstituents.xml",
        include_str!("../resources/xml/arylSubstituents.xml"),
    ),
    (
        "atomHydrides.xml",
        include_str!("../resources/xml/atomHydrides.xml"),
    ),
    (
        "carbohydrateSuffixes.xml",
        include_str!("../resources/xml/carbohydrateSuffixes.xml"),
    ),
    (
        "carbohydrates.xml",
        include_str!("../resources/xml/carbohydrates.xml"),
    ),
    (
        "carboxylicAcids.xml",
        include_str!("../resources/xml/carboxylicAcids.xml"),
    ),
    (
        "chargeAndOxidationNumberSpecifiers.xml",
        include_str!("../resources/xml/chargeAndOxidationNumberSpecifiers.xml"),
    ),
    (
        "cyclicUnsaturableHydrocarbon.xml",
        include_str!("../resources/xml/cyclicUnsaturableHydrocarbon.xml"),
    ),
    (
        "elementaryAtoms.xml",
        include_str!("../resources/xml/elementaryAtoms.xml"),
    ),
    (
        "functionalTerms.xml",
        include_str!("../resources/xml/functionalTerms.xml"),
    ),
    (
        "fusionComponents.xml",
        include_str!("../resources/xml/fusionComponents.xml"),
    ),
    (
        "germanTokens.xml",
        include_str!("../resources/xml/germanTokens.xml"),
    ),
    (
        "groupStemsAllowingAllSuffixes.xml",
        include_str!("../resources/xml/groupStemsAllowingAllSuffixes.xml"),
    ),
    (
        "groupStemsAllowingInlineSuffixes.xml",
        include_str!("../resources/xml/groupStemsAllowingInlineSuffixes.xml"),
    ),
    (
        "heteroAtoms.xml",
        include_str!("../resources/xml/heteroAtoms.xml"),
    ),
    (
        "hwHeteroAtoms.xml",
        include_str!("../resources/xml/hwHeteroAtoms.xml"),
    ),
    (
        "hwSuffixes.xml",
        include_str!("../resources/xml/hwSuffixes.xml"),
    ),
    ("index.xml", include_str!("../resources/xml/index.xml")),
    ("infixes.xml", include_str!("../resources/xml/infixes.xml")),
    (
        "inlineChargeSuffixes.xml",
        include_str!("../resources/xml/inlineChargeSuffixes.xml"),
    ),
    (
        "inlineSuffixes.xml",
        include_str!("../resources/xml/inlineSuffixes.xml"),
    ),
    (
        "miscTokens.xml",
        include_str!("../resources/xml/miscTokens.xml"),
    ),
    (
        "multiRadicalSubstituents.xml",
        include_str!("../resources/xml/multiRadicalSubstituents.xml"),
    ),
    (
        "multipliers.xml",
        include_str!("../resources/xml/multipliers.xml"),
    ),
    (
        "naturalProducts.xml",
        include_str!("../resources/xml/naturalProducts.xml"),
    ),
    (
        "nonCarboxylicAcids.xml",
        include_str!("../resources/xml/nonCarboxylicAcids.xml"),
    ),
    (
        "regexTokens.xml",
        include_str!("../resources/xml/regexTokens.xml"),
    ),
    ("regexes.xml", include_str!("../resources/xml/regexes.xml")),
    (
        "simpleCyclicGroups.xml",
        include_str!("../resources/xml/simpleCyclicGroups.xml"),
    ),
    (
        "simpleGroups.xml",
        include_str!("../resources/xml/simpleGroups.xml"),
    ),
    (
        "simpleSubstituents.xml",
        include_str!("../resources/xml/simpleSubstituents.xml"),
    ),
    (
        "substituents.xml",
        include_str!("../resources/xml/substituents.xml"),
    ),
    (
        "suffixApplicability.xml",
        include_str!("../resources/xml/suffixApplicability.xml"),
    ),
    (
        "suffixPrefix.xml",
        include_str!("../resources/xml/suffixPrefix.xml"),
    ),
    (
        "suffixRules.xml",
        include_str!("../resources/xml/suffixRules.xml"),
    ),
    (
        "suffixes.xml",
        include_str!("../resources/xml/suffixes.xml"),
    ),
    (
        "unsaturators.xml",
        include_str!("../resources/xml/unsaturators.xml"),
    ),
    (
        "wordRules.xml",
        include_str!("../resources/xml/wordRules.xml"),
    ),
];
