//! Exact tables and checks translated from OPSIN 2.9.0 ValencyChecker.java.
//! Source commit: b91b610af5ab07560fedb20730d7aef46bb2bca0 (MIT).
//! Unknown element/charge combinations are deliberately represented by None,
//! as upstream does; this is not a general chemistry valence validator.

use crate::graph::{AtomId, Element, Graph};

pub fn default_valency(element: Element) -> Option<i32> {
    match element {
        Element::B => Some(3),
        Element::Al => Some(3),
        Element::In => Some(3),
        Element::Ga => Some(3),
        Element::Tl => Some(3),
        Element::C => Some(4),
        Element::Si => Some(4),
        Element::Ge => Some(4),
        Element::Sn => Some(4),
        Element::Pb => Some(4),
        Element::N => Some(3),
        Element::P => Some(3),
        Element::As => Some(3),
        Element::Sb => Some(3),
        Element::Bi => Some(3),
        Element::O => Some(2),
        Element::S => Some(2),
        Element::Se => Some(2),
        Element::Te => Some(2),
        Element::Po => Some(2),
        Element::F => Some(1),
        Element::Cl => Some(1),
        Element::Br => Some(1),
        Element::I => Some(1),
        Element::At => Some(1),
        _ => None,
    }
}

pub fn hw_valency(element: Element) -> Option<i32> {
    match element {
        Element::F => Some(1),
        Element::Cl => Some(1),
        Element::Br => Some(1),
        Element::I => Some(1),
        Element::O => Some(2),
        Element::S => Some(2),
        Element::Se => Some(2),
        Element::Te => Some(2),
        Element::N => Some(3),
        Element::P => Some(3),
        Element::As => Some(3),
        Element::Sb => Some(3),
        Element::Bi => Some(3),
        Element::Si => Some(4),
        Element::Ge => Some(4),
        Element::Sn => Some(4),
        Element::Pb => Some(4),
        Element::B => Some(3),
        Element::Al => Some(3),
        Element::Ga => Some(3),
        Element::In => Some(3),
        Element::Tl => Some(3),
        Element::Hg => Some(2),
        Element::C => Some(4),
        _ => None,
    }
}

/// Valencies retain upstream priority order, including its unusual charged cases.
pub fn possible_valencies(element: Element, charge: i32) -> Option<&'static [i32]> {
    match (element, charge) {
        (Element::H, 0) => Some(&[1]),
        (Element::He, 0) => Some(&[0]),
        (Element::Li, 0) => Some(&[1]),
        (Element::Be, 0) => Some(&[2]),
        (Element::B, 0) => Some(&[3]),
        (Element::C, 0) => Some(&[4]),
        (Element::N, 0) => Some(&[3]),
        (Element::O, 0) => Some(&[2]),
        (Element::F, 0) => Some(&[1]),
        (Element::Ne, 0) => Some(&[0]),
        (Element::Na, 0) => Some(&[1]),
        (Element::Mg, 0) => Some(&[2]),
        (Element::Al, 0) => Some(&[3]),
        (Element::Si, 0) => Some(&[4]),
        (Element::P, 0) => Some(&[3, 5]),
        (Element::S, 0) => Some(&[2, 4, 6]),
        (Element::Cl, 0) => Some(&[1, 3, 5, 7]),
        (Element::Ar, 0) => Some(&[0]),
        (Element::K, 0) => Some(&[1]),
        (Element::Ca, 0) => Some(&[2]),
        (Element::Ga, 0) => Some(&[3]),
        (Element::Ge, 0) => Some(&[4]),
        (Element::As, 0) => Some(&[3, 5]),
        (Element::Se, 0) => Some(&[2, 4, 6]),
        (Element::Br, 0) => Some(&[1, 3, 5, 7]),
        (Element::Kr, 0) => Some(&[0, 2]),
        (Element::Rb, 0) => Some(&[1]),
        (Element::Sr, 0) => Some(&[2]),
        (Element::In, 0) => Some(&[3]),
        (Element::Sn, 0) => Some(&[2, 4]),
        (Element::Sb, 0) => Some(&[3, 5]),
        (Element::Te, 0) => Some(&[2, 4, 6]),
        (Element::I, 0) => Some(&[1, 3, 5, 7]),
        (Element::Xe, 0) => Some(&[0, 2, 4, 6, 8]),
        (Element::Cs, 0) => Some(&[1]),
        (Element::Ba, 0) => Some(&[2]),
        (Element::Tl, 0) => Some(&[1, 3]),
        (Element::Pb, 0) => Some(&[2, 4]),
        (Element::Bi, 0) => Some(&[3, 5]),
        (Element::Po, 0) => Some(&[2, 4, 6]),
        (Element::At, 0) => Some(&[1, 3, 5, 7]),
        (Element::Rn, 0) => Some(&[0, 2, 4, 6, 8]),
        (Element::Fr, 0) => Some(&[1]),
        (Element::Ra, 0) => Some(&[2]),
        (Element::H, 1) => Some(&[0]),
        (Element::Li, 1) => Some(&[0]),
        (Element::Be, 1) => Some(&[1]),
        (Element::Be, 2) => Some(&[0]),
        (Element::B, 2) => Some(&[1]),
        (Element::B, 1) => Some(&[2]),
        (Element::B, -1) => Some(&[4]),
        (Element::B, -2) => Some(&[3]),
        (Element::C, 2) => Some(&[2]),
        (Element::C, 1) => Some(&[3]),
        (Element::C, -1) => Some(&[3]),
        (Element::C, -2) => Some(&[2]),
        (Element::N, 2) => Some(&[3]),
        (Element::N, 1) => Some(&[4]),
        (Element::N, -1) => Some(&[2]),
        (Element::N, -2) => Some(&[1]),
        (Element::O, 2) => Some(&[4]),
        (Element::O, 1) => Some(&[3, 5]),
        (Element::O, -1) => Some(&[1]),
        (Element::O, -2) => Some(&[0]),
        (Element::F, 2) => Some(&[3, 5]),
        (Element::F, 1) => Some(&[2]),
        (Element::F, -1) => Some(&[0]),
        (Element::Na, 1) => Some(&[0]),
        (Element::Na, -1) => Some(&[0]),
        (Element::Mg, 2) => Some(&[0]),
        (Element::Al, 3) => Some(&[0]),
        (Element::Al, 2) => Some(&[1]),
        (Element::Al, 1) => Some(&[2]),
        (Element::Al, -1) => Some(&[4]),
        (Element::Al, -2) => Some(&[3, 5]),
        (Element::Si, 2) => Some(&[2]),
        (Element::Si, 1) => Some(&[3]),
        (Element::Si, -1) => Some(&[3, 5]),
        (Element::Si, -2) => Some(&[2]),
        (Element::P, 2) => Some(&[3]),
        (Element::P, 1) => Some(&[4]),
        (Element::P, -1) => Some(&[2, 4, 6]),
        (Element::P, -2) => Some(&[1, 3, 5, 7]),
        (Element::S, 2) => Some(&[4]),
        (Element::S, 1) => Some(&[3, 5]),
        (Element::S, -1) => Some(&[1, 3, 5, 7]),
        (Element::S, -2) => Some(&[0]),
        (Element::Cl, 2) => Some(&[3, 5]),
        (Element::Cl, 1) => Some(&[2, 4, 6]),
        (Element::Cl, -1) => Some(&[0]),
        (Element::K, 1) => Some(&[0]),
        (Element::K, -1) => Some(&[0]),
        (Element::Ca, 2) => Some(&[0]),
        (Element::Ca, 1) => Some(&[1]),
        (Element::Ga, 3) => Some(&[0]),
        (Element::Ga, 2) => Some(&[1]),
        (Element::Ga, 1) => Some(&[0]),
        (Element::Ga, -1) => Some(&[4]),
        (Element::Ga, -2) => Some(&[3, 5]),
        (Element::Ge, 4) => Some(&[0]),
        (Element::Ge, 1) => Some(&[3]),
        (Element::Ge, -1) => Some(&[3, 5]),
        (Element::Ge, -2) => Some(&[2, 4, 6]),
        (Element::As, 2) => Some(&[3]),
        (Element::As, 1) => Some(&[4]),
        (Element::As, -1) => Some(&[2, 4, 6]),
        (Element::As, -2) => Some(&[1, 3, 5, 7]),
        (Element::As, -3) => Some(&[0]),
        (Element::Se, 2) => Some(&[4]),
        (Element::Se, 1) => Some(&[3, 5]),
        (Element::Se, -1) => Some(&[1, 3, 5, 7]),
        (Element::Se, -2) => Some(&[0]),
        (Element::Br, 2) => Some(&[3, 5]),
        (Element::Br, 1) => Some(&[2, 4, 6]),
        (Element::Br, -1) => Some(&[0]),
        (Element::Rb, 1) => Some(&[0]),
        (Element::Rb, -1) => Some(&[0]),
        (Element::Sr, 2) => Some(&[0]),
        (Element::Sr, 1) => Some(&[1]),
        (Element::In, 3) => Some(&[0]),
        (Element::In, 2) => Some(&[1]),
        (Element::In, 1) => Some(&[0]),
        (Element::In, -1) => Some(&[2, 4]),
        (Element::In, -2) => Some(&[3, 5]),
        (Element::Sn, 4) => Some(&[0]),
        (Element::Sn, 2) => Some(&[0]),
        (Element::Sn, 1) => Some(&[3]),
        (Element::Sn, -1) => Some(&[3, 5]),
        (Element::Sn, -2) => Some(&[2, 4, 6]),
        (Element::Sb, 3) => Some(&[0]),
        (Element::Sb, 2) => Some(&[3]),
        (Element::Sb, 1) => Some(&[2, 4]),
        (Element::Sb, -1) => Some(&[2, 4, 6]),
        (Element::Sb, -2) => Some(&[1, 3, 5, 7]),
        (Element::Te, 2) => Some(&[2, 4]),
        (Element::Te, 1) => Some(&[3, 5]),
        (Element::Te, -1) => Some(&[1, 3, 5, 7]),
        (Element::Te, -2) => Some(&[0]),
        (Element::I, 2) => Some(&[3, 5]),
        (Element::I, 1) => Some(&[2, 4, 6]),
        (Element::I, -1) => Some(&[0]),
        (Element::Cs, 1) => Some(&[0]),
        (Element::Cs, -1) => Some(&[0]),
        (Element::Ba, 2) => Some(&[0]),
        (Element::Ba, 1) => Some(&[1]),
        (Element::Pb, 2) => Some(&[0]),
        (Element::Pb, 1) => Some(&[3]),
        (Element::Pb, -1) => Some(&[3, 5]),
        (Element::Pb, -2) => Some(&[2, 4, 6]),
        (Element::Bi, 3) => Some(&[0]),
        (Element::Bi, 2) => Some(&[3]),
        (Element::Bi, 1) => Some(&[2, 4]),
        (Element::Bi, -1) => Some(&[2, 4, 6]),
        (Element::Bi, -2) => Some(&[1, 3, 5, 7]),
        (Element::At, 2) => Some(&[3, 5]),
        (Element::At, 1) => Some(&[2, 4, 6]),
        (Element::At, -1) => Some(&[0]),
        (Element::Fr, 1) => Some(&[0]),
        (Element::Ra, 2) => Some(&[0]),
        (Element::Ra, 1) => Some(&[1]),
        _ => None,
    }
}

pub fn maximum_valency(element: Element, charge: i32) -> Option<i32> {
    possible_valencies(element, charge).and_then(|values| values.last().copied())
}

pub fn maximum_atom_valency(graph: &Graph, atom: AtomId) -> Option<i32> {
    let atom = graph.atom(atom);
    atom.lambda_convention_valency
        .map(|value| value + atom.protons_explicitly_added_or_removed)
        .or_else(|| maximum_valency(atom.element, atom.charge))
}

pub fn check_valency(graph: &Graph, atom: AtomId) -> bool {
    maximum_atom_valency(graph, atom).is_none_or(|maximum| {
        graph.incoming_valency(atom) + graph.atom(atom).out_valency <= maximum
    })
}

/// Spare and out valency are intentionally ignored in this upstream check.
pub fn check_valency_available_for_bond(graph: &Graph, atom: AtomId, order: i32) -> bool {
    maximum_atom_valency(graph, atom)
        .is_none_or(|maximum| graph.incoming_valency(atom) + order <= maximum)
}

pub fn check_valency_available_for_replacement(
    graph: &Graph,
    atom: AtomId,
    replacement: AtomId,
) -> bool {
    let a = graph.atom(atom);
    let replacement = graph.atom(replacement);
    let valency = graph.incoming_valency(atom) + i32::from(a.spare_valency) + a.out_valency;
    maximum_valency(replacement.element, replacement.charge)
        .is_none_or(|maximum| valency <= maximum)
}

/// Exact Pauling table from the pinned upstream AtomProperties.java.
pub fn pauling_electronegativity(element: Element) -> Option<f64> {
    match element {
        Element::H => Some(2.20),
        Element::Li => Some(0.98),
        Element::Be => Some(1.57),
        Element::B => Some(2.04),
        Element::C => Some(2.55),
        Element::N => Some(3.04),
        Element::O => Some(3.44),
        Element::F => Some(3.98),
        Element::Na => Some(0.93),
        Element::Mg => Some(1.31),
        Element::Al => Some(1.61),
        Element::Si => Some(1.90),
        Element::P => Some(2.19),
        Element::S => Some(2.58),
        Element::Cl => Some(3.16),
        Element::K => Some(0.82),
        Element::Ca => Some(1.00),
        Element::Sc => Some(1.36),
        Element::Ti => Some(1.54),
        Element::V => Some(1.63),
        Element::Cr => Some(1.66),
        Element::Mn => Some(1.55),
        Element::Fe => Some(1.83),
        Element::Co => Some(1.88),
        Element::Ni => Some(1.91),
        Element::Cu => Some(1.90),
        Element::Zn => Some(1.65),
        Element::Ga => Some(1.81),
        Element::Ge => Some(2.01),
        Element::As => Some(2.18),
        Element::Se => Some(2.55),
        Element::Br => Some(2.96),
        Element::Kr => Some(3.00),
        Element::Rb => Some(0.82),
        Element::Sr => Some(0.95),
        Element::Y => Some(1.22),
        Element::Zr => Some(1.33),
        Element::Nb => Some(1.6),
        Element::Mo => Some(2.16),
        Element::Tc => Some(1.9),
        Element::Ru => Some(2.2),
        Element::Rh => Some(2.28),
        Element::Pd => Some(2.20),
        Element::Ag => Some(1.93),
        Element::Cd => Some(1.69),
        Element::In => Some(1.78),
        Element::Sn => Some(1.96),
        Element::Sb => Some(2.05),
        Element::Te => Some(2.1),
        Element::I => Some(2.66),
        Element::Xe => Some(2.60),
        Element::Cs => Some(0.79),
        Element::Ba => Some(0.89),
        Element::La => Some(1.1),
        Element::Ce => Some(1.12),
        Element::Pr => Some(1.13),
        Element::Nd => Some(1.14),
        Element::Pm => Some(1.13),
        Element::Sm => Some(1.17),
        Element::Eu => Some(1.2),
        Element::Gd => Some(1.2),
        Element::Tb => Some(1.1),
        Element::Dy => Some(1.22),
        Element::Ho => Some(1.23),
        Element::Er => Some(1.24),
        Element::Tm => Some(1.25),
        Element::Yb => Some(1.1),
        Element::Lu => Some(1.27),
        Element::Hf => Some(1.3),
        Element::Ta => Some(1.5),
        Element::W => Some(2.36),
        Element::Re => Some(1.9),
        Element::Os => Some(2.2),
        Element::Ir => Some(2.20),
        Element::Pt => Some(2.28),
        Element::Au => Some(2.54),
        Element::Hg => Some(2.00),
        Element::Tl => Some(1.62),
        Element::Pb => Some(2.33),
        Element::Bi => Some(2.02),
        Element::Po => Some(2.0),
        Element::At => Some(2.2),
        Element::Rn => Some(2.2),
        Element::Fr => Some(0.7),
        Element::Ra => Some(0.9),
        Element::Ac => Some(1.1),
        Element::Th => Some(1.3),
        Element::Pa => Some(1.5),
        Element::U => Some(1.38),
        Element::Np => Some(1.36),
        Element::Pu => Some(1.28),
        Element::Am => Some(1.13),
        Element::Cm => Some(1.28),
        Element::Bk => Some(1.3),
        Element::Cf => Some(1.3),
        Element::Es => Some(1.3),
        Element::Fm => Some(1.3),
        Element::Md => Some(1.3),
        Element::No => Some(1.3),
        Element::Lr => Some(1.3),
        _ => None,
    }
}

/// Exact Hantzsch-Widman priority table from AtomProperties.java.
pub fn hw_priority(element: Element) -> Option<i32> {
    match element {
        Element::F => Some(23),
        Element::Cl => Some(22),
        Element::Br => Some(21),
        Element::I => Some(20),
        Element::O => Some(19),
        Element::S => Some(18),
        Element::Se => Some(17),
        Element::Te => Some(16),
        Element::N => Some(15),
        Element::P => Some(14),
        Element::As => Some(13),
        Element::Sb => Some(12),
        Element::Bi => Some(11),
        Element::Si => Some(10),
        Element::Ge => Some(9),
        Element::Sn => Some(8),
        Element::Pb => Some(7),
        Element::B => Some(6),
        Element::Al => Some(5),
        Element::Ga => Some(4),
        Element::In => Some(3),
        Element::Tl => Some(2),
        Element::Hg => Some(1),
        _ => None,
    }
}
