use super::{Cancel, Identity, Provenance, Record, local, rules, worker};
use std::process::{Command, Stdio};

const LIMITS: reshiki_process::Limits = reshiki_process::Limits {
    address_bytes: 8 * 1024 * 1024 * 1024,
    memory_bytes: 384 * 1024 * 1024,
    cpu_seconds: 20,
    file_bytes: 8 * 1024 * 1024,
};
static SLOTS: tokio::sync::Semaphore = tokio::sync::Semaphore::const_new(1);
struct StopOnDrop(Cancel);
impl Drop for StopOnDrop {
    fn drop(&mut self) {
        self.0.stop();
    }
}

fn generate_worker(smiles: &str, cancel: &Cancel) -> Result<String, String> {
    if cancel.stopped() {
        return Err("Local name generation was cancelled".into());
    }
    let request = serde_json::to_vec(&worker::Request::Generate {
        protocol: worker::PROTOCOL,
        profile: rules::PROFILE.into(),
        smiles: smiles.into(),
    })
    .map_err(|e| e.to_string())?;
    if request.len() > worker::WIRE_LIMIT {
        return Err("Local naming request exceeds its wire limit".into());
    }
    let directory = tempfile::Builder::new()
        .prefix("reshiki-name-rules-")
        .tempdir()
        .map_err(|e| e.to_string())?;
    let mut command = Command::new(worker::executable()?);
    command
        .arg("--naming-worker")
        .current_dir(directory.path())
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .stderr(Stdio::piped());
    let bytes = local::run_child(&mut command, &request, cancel, LIMITS)?;
    parse_response(&bytes, smiles)
}
fn parse_response(bytes: &[u8], smiles: &str) -> Result<String, String> {
    if bytes.len() > worker::WIRE_LIMIT {
        return Err("Local rule response exceeds its wire limit".into());
    }
    let response: worker::Response = serde_json::from_slice(bytes)
        .map_err(|_| "Local naming rules returned an invalid structured result")?;
    let worker::Response::Generate(response) = response else {
        return Err("Local rules returned a result for a different operation".into());
    };
    if response.protocol != worker::PROTOCOL
        || response.profile != rules::PROFILE
        || response.input != smiles
    {
        return Err("Local rule result has inconsistent profile or input identity".into());
    }
    let name = response.result?;
    if name.is_empty() || name.len() > 2048 || name.chars().any(char::is_control) {
        return Err("Local naming rules returned an invalid name".into());
    }
    Ok(name)
}

/// A name is returned only after the pinned local decoder exactly reconstructs
/// the native graph. Decoder equivalence is separate from the rule tests.
pub async fn generate_name(identity: &Identity, cancel: Cancel) -> Result<Record, String> {
    let expected = super::canonical_smiles(&identity.smiles)?;
    let stop = StopOnDrop(cancel.clone());
    let permit = tokio::select! {
        p=SLOTS.acquire()=>p.map_err(|_|"Local naming rules are unavailable")?,
        ()=cancel.cancelled()=>return Err("Local name generation was cancelled".into()),
    };
    let input = expected.clone();
    let worker_cancel = cancel.clone();
    let candidate = tokio::task::spawn_blocking(move || {
        let _permit = permit;
        generate_worker(&input, &worker_cancel)
    })
    .await
    .map_err(|e| format!("Local naming worker failed: {e}"))??;
    if cancel.stopped() {
        return Err("Local name generation was cancelled".into());
    }
    // Use a separate token: resolve_name's drop guard stops its own operation,
    // while this guard continues to cover cancellation of the whole pipeline.
    let decoder = Cancel::default();
    let reconstructed = tokio::select! {
        r=super::resolve_name(&candidate,decoder.clone())=>r?,
        ()=cancel.cancelled()=>{decoder.stop();return Err("Local name generation was cancelled".into());},
    };
    super::verify_identity(&expected, &reconstructed.smiles)
        .map_err(|e| format!("Local rule reconstruction failed: {e}"))?;
    drop(stop);
    let mut warnings = identity.warnings.clone();
    warnings.push(format!("Generated by {} and exactly reconstructed by the OPSIN Rust port. General systematic-name subset; preferred IUPAC name (PIN) selection is not claimed.",rules::PROFILE));
    Ok(Record {
        title: candidate.clone(),
        systematic_name: Some(candidate),
        smiles: expected.clone(),
        canonical_smiles: expected,
        synonyms: vec![],
        warnings,
        provenance: Provenance::LocalRules,
    })
}

#[cfg(test)]
mod tests;
