//! Independent C++ standard-library snapshots, generated by
//! tests/smiles_sort_reference.cpp on each assigned validation host.
use super::Error;
use serde::Deserialize;

type Entry = (i32, usize);

fn input(n: usize, pattern: usize) -> anyhow::Result<Vec<Entry>> {
    let mut random = 39103_u32;
    (0..n)
        .map(|i| {
            random = random.wrapping_mul(1664525).wrapping_add(1013904223);
            let key = match pattern {
                0 => i64::try_from(i / 3)?,
                1 => i64::try_from((n - i) / 3)?,
                2 => 0,
                3 => i64::try_from(i % 3)?,
                4 => i64::try_from(i.min(n - i))?,
                5 => i64::from(random % 7),
                6 => i64::from(random % 31),
                7 => i64::from(random) - 2147483648,
                8 => i64::try_from((i % 17) / 2)?,
                9 => {
                    if i == n / 2 {
                        0
                    } else {
                        i64::try_from(i)?
                    }
                }
                10 => i64::try_from(i % 2)?,
                11 => i64::try_from(if random.is_multiple_of(2) {
                    i / 2
                } else {
                    (n - i) / 2
                })?,
                _ => anyhow::bail!("Unknown fixture pattern"),
            };
            Ok((i32::try_from(key)?, i))
        })
        .collect()
}

fn fingerprint(values: &[Entry]) -> anyhow::Result<u64> {
    values
        .iter()
        .try_fold(14695981039346656037_u64, |hash, (_, edge)| {
            Ok(u64::try_from(*edge)?
                .to_le_bytes()
                .iter()
                .fold(hash, |hash, byte| {
                    (hash ^ u64::from(*byte)).wrapping_mul(1099511628211)
                }))
        })
}

fn sort(values: &mut [Entry], heap: bool) -> Result<(), Error> {
    #[cfg(target_os = "linux")]
    return if heap {
        super::linux_sort::heap(values, 0, values.len())
    } else {
        super::linux_sort::sort(values)
    };
    #[cfg(target_os = "macos")]
    return if heap {
        super::sort_common::heap(values, 0, values.len(), false)
    } else {
        super::apple_sort::sort(values)
    };
    #[cfg(target_os = "windows")]
    return if heap {
        super::sort_common::heap(values, 0, values.len(), true)
    } else {
        super::windows_sort::sort(values)
    };
}

#[derive(Deserialize)]
struct Reference {
    library: String,
    cases: Vec<(usize, usize, String, String)>,
}

#[test]
fn equal_keys_match_native_sort_and_heap_fallback() -> anyhow::Result<()> {
    #[cfg(target_os = "linux")]
    let source = include_str!("../../../tests/fixtures/smiles-sort-linux.json");
    #[cfg(target_os = "macos")]
    let source = include_str!("../../../tests/fixtures/smiles-sort-macos.json");
    #[cfg(target_os = "windows")]
    let source = include_str!("../../../tests/fixtures/smiles-sort-windows.json");
    let reference: Reference = serde_json::from_str(source)?;
    for (n, pattern, sorted, heap) in reference.cases {
        for (is_heap, expected) in [(false, sorted), (true, heap)] {
            let original = input(n, pattern)?;
            let mut values = original.clone();
            sort(&mut values, is_heap)?;
            anyhow::ensure!(
                fingerprint(&values)? == expected.parse::<u64>()?,
                "{}: n={n}, pattern={pattern}, heap={is_heap}",
                reference.library
            );
            assert!(values.windows(2).all(|w| w[0].0 <= w[1].0));
            let mut ids = values.iter().map(|(_, edge)| *edge).collect::<Vec<_>>();
            ids.sort_unstable();
            assert_eq!(ids, (0..n).collect::<Vec<_>>());
            for (key, edge) in values {
                assert_eq!(original.get(edge).map(|e| e.0), Some(key));
            }
        }
    }
    Ok(())
}
