"""Regenerate preview/placement coordinates with Moruno's own chemistry worker.

Run: uv run --locked python scripts/regenerate_templates.py
The catalog contains frozen PubChem chemical facts and source URLs. Amino acids
are built with RDKit's L-protein sequence builder and checked against PubChem's
formula and standard InChIKey. No reference-editor assets are used. Chair
geometry is generated by src/rings.rs. This script needs no network access.
"""

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
from rdkit import Chem  # noqa: E402
from rdkit.Chem import rdMolDescriptors  # noqa: E402

from engine.worker import handle  # noqa: E402

path = ROOT / "assets/templates.json"
catalog = json.loads((ROOT / "assets/template-catalog.json").read_text())
library = []
for entry in catalog:
    mol = (
        Chem.MolFromSequence(entry["sequence"], flavor=0)
        if entry.get("sequence")
        else Chem.MolFromSmiles(entry["smiles"])
    )
    assert mol is not None, entry["name"]
    assert rdMolDescriptors.CalcMolFormula(mol) == entry["formula"], entry["name"]
    assert Chem.MolToInchiKey(mol) == entry["inchikey"], entry["name"]
    template = {k: entry[k] for k in ("name", "group")}
    template["smiles"] = Chem.MolToSmiles(mol)
    template["keywords"] = entry.get("keywords", [])
    template["note"] = entry.get("note", "")
    if entry["name"] == "Decalin":
        template["note"] = "Ring-junction stereochemistry is unspecified."
    template["document"] = handle(
        {
            "protocol": 1,
            "operation": "import",
            "format": "smiles",
            "text": template["smiles"],
        }
    )["document"]
    library.append(template)
path.write_text(json.dumps(library, indent=2) + "\n")
print(f"Regenerated {len(library)} templates")
