"""Generate the Rust codec's constants from the checked Python reference schema."""

import json
import struct
import sys
from pathlib import Path


def main():
    root = Path(__file__).resolve().parents[1]
    sys.path.insert(0, str(root))
    from engine.cdx_exchange import PROPERTIES

    lines = [
        "// Generated by scripts/regenerate_cdx_rust_schema.py; do not edit.",
        "// Format source and corrections: engine/cdx_schema.py, engine/cdx_exchange.py.",
        "use super::Property;",
        "pub(super) const PROPERTIES: &[Property] = &[",
    ]
    for code, (name, kind, enum) in PROPERTIES.items():
        variants = ", ".join(f"({json.dumps(k)}, {v})" for k, v in enum.items())
        lines.append(
            f"    Property {{ code: 0x{code:04x}, name: {json.dumps(name)}, "
            f"kind: {json.dumps(kind)}, variants: &[{variants}] }},"
        )
    lines.append("];")
    (root / "src/exchange/schema.rs").write_text("\n".join(lines) + "\n")

    # Use the exact historical codepages, not their similarly named WHATWG
    # variants. Store Unicode scalars as u32; 0xffffffff marks undefined bytes.
    target = root / "src/exchange/charsets"
    target.mkdir(exist_ok=True)
    for charset, encoding in [
        (10000, "mac_roman"),
        (1252, "cp1252"),
        (1251, "cp1251"),
        (932, "cp932"),
        (936, "gbk"),
        (949, "cp949"),
        (950, "big5"),
    ]:
        single = bytearray()
        pairs = bytearray()
        for code in range(65536 if charset in (932, 936, 949, 950) else 256):
            raw = bytes([code]) if code < 256 else code.to_bytes(2, "big")
            try:
                text = raw.decode(encoding)
            except UnicodeError:
                text = ""
            point = ord(text) if len(text) == 1 else 0xFFFFFFFF
            if code < 256:
                single.extend(struct.pack("<I", point))
            elif point != 0xFFFFFFFF:
                pairs.extend(struct.pack("<HI", code, point))
        (target / f"{encoding}.bin").write_bytes(single + pairs)


if __name__ == "__main__":
    main()
