"""Extract Rust mass tables from the pinned RDKit source, checking the local oracle."""

import argparse
import hashlib
import json
import re
from pathlib import Path

from rdkit import Chem, rdBase

VERSION = "2026.03.6"
COMMIT = "0e0d85f4ca34aeae15dfc0f7cf5503bdb0a8e985"
SOURCE_SHA256 = "7f9cee6e430b60d303a0a7fa9e33c45e5c529ee204f86afeab6a20f68b6b0631"
ROOT = Path(__file__).resolve().parents[1]


def raw_strings(text):
    return "\n".join(re.findall(r'R"DAT\((.*?)\)DAT"', text, re.DOTALL))


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--rdkit-source", type=Path, default=Path.home() / "dev/rdkit")
    args = parser.parse_args()
    source = (args.rdkit_source / "Code/GraphMol/atomic_data.cpp").read_bytes()
    if hashlib.sha256(source).hexdigest() != SOURCE_SHA256 or rdBase.rdkitVersion != VERSION:
        raise ValueError(f"Expected RDKit {VERSION} source at {COMMIT} and matching Python package")
    text = source.decode("utf-8")
    periodic = raw_strings(
        text.split("periodicTableAtomData =", 1)[1].split("// Names of elements", 1)[0]
    )
    elements = {}
    table = Chem.GetPeriodicTable()
    for line in periodic.splitlines():
        fields = line.split()
        if not fields:
            continue
        number, symbol = int(fields[0]), fields[1]
        if number in elements:  # RDKit retains the first name, not historical aliases.
            continue
        average, exact = float(fields[6]), float(fields[9])
        if (symbol, average, exact) != (
            table.GetElementSymbol(number),
            table.GetAtomicWeight(number),
            table.GetMostCommonIsotopeMass(number),
        ):
            raise ValueError(f"Element {number} differs from the installed RDKit")
        elements[number] = (symbol, average, exact)
    if sorted(elements) != list(range(119)):
        raise ValueError("Incomplete periodic table")
    isotopes = {}
    for line in raw_strings(text.split("isotopesAtomData[] =", 1)[1]).splitlines():
        fields = line.split()
        if not fields:
            continue
        number, isotope, mass = int(fields[0]), int(fields[2]), float(fields[3])
        if table.GetMassForIsotope(number, isotope) != mass:
            raise ValueError(f"Isotope {number}/{isotope} differs from the installed RDKit")
        key = (number, isotope)
        if key in isotopes:
            raise ValueError(f"Duplicate isotope {key}")
        isotopes[key] = mass
    # Check independently for skipped source rows as well as changed values.
    known = {
        (number, isotope): mass
        for number in range(119)
        for isotope in range(1, 401)
        if (mass := table.GetMassForIsotope(number, isotope))
    }
    if isotopes != known:
        raise ValueError("Incomplete isotope table")
    lines = [
        "// Generated by scripts/regenerate_atomic_data.py; do not edit.",
        f"// RDKit {VERSION}, Code/GraphMol/atomic_data.cpp at {COMMIT}.",
        "// Copyright (C) 2001-2024 Greg Landrum and other RDKit contributors.",
        "// BSD-3-Clause; see licenses/rdkit/LICENSE and NOTICE.",
        "use super::Element;",
        f'pub const RDKIT_VERSION: &str = "{VERSION}";',
        "pub(super) const ELECTRON_MASS: f64 = 0.00054857991;",
        "pub(super) const ELEMENTS: &[Element] = &[",
    ]
    for symbol, average, exact in elements.values():
        lines.append(
            f"    Element {{ symbol: {json.dumps(symbol)}, average: {average!r}, exact: {exact!r} }},"
        )
    lines.extend(
        [
            "];",
            "pub(super) const ISOTOPES: &[(u8, u16, f64)] = &[",
            *(f"    ({n}, {i}, {m!r})," for (n, i), m in sorted(isotopes.items())),
            "];",
        ]
    )
    (ROOT / "src/chemistry/atomic_data.rs").write_text("\n".join(lines) + "\n")
    print(f"Generated {len(elements)} elements and {len(isotopes)} isotopes for RDKit {VERSION}")


if __name__ == "__main__":
    main()
