import { defineConfig } from "astro/config";
import starlight from "@astrojs/starlight";

export default defineConfig({
  site: "https://ameyanagi.github.io",
  base: "/moruno",
  redirects: {
    "/reference/abbreviations": "/moruno/guide/labels/",
    "/reference/architecture": "/moruno/developer/architecture/",
    "/reference/arrows": "/moruno/guide/reactions/",
    "/reference/assistant": "/moruno/guide/assistant/",
    "/reference/atom-labels": "/moruno/guide/labels/",
    "/reference/bond-tools": "/moruno/guide/first-molecule/",
    "/reference/capabilities": "/moruno/developer/capabilities/",
    "/reference/chain-tools": "/moruno/guide/first-molecule/",
    "/reference/changes-0.2": "/moruno/developer/changes-0.2/",
    "/reference/clipboard": "/moruno/guide/sharing/",
    "/reference/contextual-shortcuts": "/moruno/guide/editing/",
    "/reference/development": "/moruno/developer/development/",
    "/reference/drawing-styles": "/moruno/guide/figures/",
    "/reference/feature-status": "/moruno/developer/feature-status/",
    "/reference/fragment-joining": "/moruno/guide/templates/",
    "/reference/framework-research": "/moruno/developer/framework-research/",
    "/reference/getting-started": "/moruno/guide/install/",
    "/reference/graphics": "/moruno/guide/figures/",
    "/reference/jacs-style": "/moruno/guide/figures/",
    "/reference/pictures": "/moruno/guide/figures/",
    "/reference/publication-pages": "/moruno/guide/figures/",
    "/reference/reactions": "/moruno/guide/reactions/",
    "/reference/releasing": "/moruno/developer/releasing/",
    "/reference/ring-presets": "/moruno/guide/templates/",
    "/reference/roadmap": "/moruno/developer/roadmap/",
    "/reference/runtime-safety": "/moruno/developer/runtime-safety/",
    "/reference/ruviz-integration": "/moruno/developer/ruviz-integration/",
    "/reference/scientific-symbols": "/moruno/guide/figures/",
    "/reference/selection-and-groups": "/moruno/guide/editing/",
    "/reference/selection-and-ring-placement": "/moruno/developer/selection-and-ring-placement/",
    "/reference/selection-cleanup": "/moruno/guide/editing/",
    "/reference/selection-transforms": "/moruno/guide/editing/",
    "/reference/template-library": "/moruno/guide/templates/",
    "/reference/template-placement": "/moruno/guide/templates/",
    "/reference/tool-palettes": "/moruno/guide/first-molecule/",
    "/reference/typography": "/moruno/guide/labels/",
    "/reference/workspace-review": "/moruno/developer/workspace-review/",
  },
  integrations: [
    starlight({
      title: "Moruno",
      description: "Draw molecules, build reaction schemes, and prepare publication figures.",
      social: [{ icon: "github", label: "GitHub", href: "https://github.com/Ameyanagi/moruno" }],
      customCss: ["./src/styles/custom.css"],
      sidebar: [
        {
          label: "User guide",
          items: [
            { label: "Install Moruno", slug: "guide/install" },
            { label: "Draw your first molecule", slug: "guide/first-molecule" },
            { label: "Build with templates", slug: "guide/templates" },
            { label: "Select and edit", slug: "guide/editing" },
            { label: "Labels and abbreviations", slug: "guide/labels" },
            { label: "Draw a reaction", slug: "guide/reactions" },
            { label: "Draw with the assistant", slug: "guide/assistant" },
            { label: "Prepare a figure", slug: "guide/figures" },
            { label: "Save and share", slug: "guide/sharing" },
          ],
        },
        {
          label: "Developer",
          collapsed: true,
          items: [
            { label: "Build and test", slug: "developer/development" },
            { label: "Architecture", slug: "developer/architecture" },
            { label: "Release and signing", slug: "developer/releasing" },
            { label: "Runtime safety", slug: "developer/runtime-safety" },
            { label: "Feature status", slug: "developer/feature-status" },
            {
              label: "Engineering notes",
              collapsed: true,
              items: [
                "abbreviations",
                "arrows",
                "assistant",
                "atom-labels",
                "bond-tools",
                "capabilities",
                "chain-tools",
                "changes-0.2",
                "clipboard",
                "contextual-shortcuts",
                "drawing-styles",
                "fragment-joining",
                "framework-research",
                "getting-started",
                "graphics",
                "jacs-style",
                "pictures",
                "publication-pages",
                "reactions",
                "ring-presets",
                "roadmap",
                "ruviz-integration",
                "scientific-symbols",
                "selection-and-groups",
                "selection-and-ring-placement",
                "selection-cleanup",
                "selection-transforms",
                "template-library",
                "template-placement",
                "tool-palettes",
                "typography",
                "workspace-review",
              ].map((name) => ({ slug: `developer/${name}` })),
            },
          ],
        },
      ],
    }),
  ],
});
