import { defineConfig } from "astro/config";
import starlight from "@astrojs/starlight";

export default defineConfig({
  site: "https://reshiki.com",
  base: "/",
  redirects: {
    "/reference/abbreviations": "/guide/labels/",
    "/reference/architecture": "/developer/architecture/",
    "/reference/arrows": "/guide/reactions/",
    "/reference/assistant": "/guide/assistant/",
    "/reference/atom-labels": "/guide/labels/",
    "/reference/bond-tools": "/guide/first-molecule/",
    "/reference/capabilities": "/developer/capabilities/",
    "/reference/chain-tools": "/guide/first-molecule/",
    "/reference/changes-0.2": "/developer/changes-0.2/",
    "/reference/clipboard": "/guide/sharing/",
    "/reference/contextual-shortcuts": "/guide/editing/",
    "/reference/development": "/developer/development/",
    "/reference/drawing-styles": "/guide/figures/",
    "/reference/feature-status": "/developer/feature-status/",
    "/reference/fragment-joining": "/guide/templates/",
    "/reference/framework-research": "/developer/framework-research/",
    "/reference/getting-started": "/guide/install/",
    "/reference/graphics": "/guide/figures/",
    "/reference/jacs-style": "/guide/figures/",
    "/reference/pictures": "/guide/figures/",
    "/reference/publication-pages": "/guide/figures/",
    "/reference/reactions": "/guide/reactions/",
    "/reference/releasing": "/developer/releasing/",
    "/reference/ring-presets": "/guide/templates/",
    "/reference/roadmap": "/developer/roadmap/",
    "/reference/runtime-safety": "/developer/runtime-safety/",
    "/reference/ruviz-integration": "/developer/ruviz-integration/",
    "/reference/scientific-symbols": "/guide/figures/",
    "/reference/selection-and-groups": "/guide/editing/",
    "/reference/selection-and-ring-placement": "/developer/selection-and-ring-placement/",
    "/reference/selection-cleanup": "/guide/editing/",
    "/reference/selection-transforms": "/guide/editing/",
    "/reference/template-library": "/guide/templates/",
    "/reference/template-placement": "/guide/templates/",
    "/reference/tool-palettes": "/guide/first-molecule/",
    "/reference/typography": "/guide/labels/",
    "/reference/workspace-review": "/developer/workspace-review/",
  },
  integrations: [
    starlight({
      title: "ReShiki",
      description: "Draw molecules, build reaction schemes, and prepare publication figures.",
      social: [
        { icon: "github", label: "Star on GitHub", href: "https://github.com/Ameyanagi/ReShiki" },
        {
          icon: "heart",
          label: "Sponsor this work",
          href: "https://github.com/sponsors/Ameyanagi",
        },
      ],
      customCss: ["./src/styles/custom.css"],
      components: { Header: "./src/components/DocsHeader.astro" },
      sidebar: [
        {
          label: "User guide",
          items: [
            { label: "Install ReShiki", slug: "guide/install" },
            { label: "Windows", slug: "guide/windows" },
            { label: "Draw your first molecule", slug: "guide/first-molecule" },
            { label: "Build with templates", slug: "guide/templates" },
            { label: "Select and edit", slug: "guide/editing" },
            { label: "Labels and abbreviations", slug: "guide/labels" },
            { label: "Draw a reaction", slug: "guide/reactions" },
            { label: "Draw with the assistant", slug: "guide/assistant" },
            { label: "Prepare a figure", slug: "guide/figures" },
            { label: "Save and share", slug: "guide/sharing" },
          ],
        },
        {
          label: "Developer",
          collapsed: true,
          items: [
            { label: "Build and test", slug: "developer/development" },
            { label: "Architecture", slug: "developer/architecture" },
            { label: "Release and signing", slug: "developer/releasing" },
            { label: "ReShiki 0.3.0", slug: "developer/changes-0.3" },
            { label: "ReShiki 0.4.0", slug: "developer/changes-0.4" },
            { label: "ReShiki 0.5.0", slug: "developer/changes-0.5" },
            { label: "ReShiki 0.6.0", slug: "developer/changes-0.6" },
            { label: "Runtime safety", slug: "developer/runtime-safety" },
            { label: "Feature status", slug: "developer/feature-status" },
            {
              label: "Engineering notes",
              collapsed: true,
              items: [
                "abbreviations",
                "arrows",
                "assistant",
                "atom-labels",
                "bond-tools",
                "capabilities",
                "chain-tools",
                "changes-0.2",
                "clipboard",
                "contextual-shortcuts",
                "drawing-styles",
                "fragment-joining",
                "framework-research",
                "getting-started",
                "graphics",
                "jacs-style",
                "pictures",
                "publication-pages",
                "reactions",
                "ring-presets",
                "roadmap",
                "ruviz-integration",
                "scientific-symbols",
                "selection-and-groups",
                "selection-and-ring-placement",
                "selection-cleanup",
                "selection-transforms",
                "template-library",
                "template-placement",
                "tool-palettes",
                "typography",
                "workspace-review",
              ].map((name) => ({ slug: `developer/${name}` })),
            },
          ],
        },
      ],
    }),
  ],
});
