// Frozen parser acceptance examples transcribed from pinned OPSIN 2.9.0
// SMILESFragmentBuilderTest.java, b91b610af5ab07560fedb20730d7aef46bb2bca0 (MIT).
// Graph-state assertions live in graph_construction.rs.
use opsin::{graph::Graph, smiles::build_fragment};

#[test]
fn upstream_resource_parser_acceptance_examples() {
    let fixtures: &[(&str, &str, bool)] = &[
        ("testBuild", "C", true),
        ("testSimple1", "CC", true),
        ("testSimple2", "O=C=O", true),
        ("testSimple3", "C#N", true),
        ("testSimple4", "CCN(CC)CC", true),
        ("testSimple5", "CC(=O)O", true),
        ("testSimple6", "C1CCCCC1", true),
        ("testSimple7", "c1ccccc1", true),
        ("testSimple8", "[I-].[Na+]", true),
        ("testSimple9", "(C(=O)O)", true),
        ("testSimple10", "C-C-O", true),
        ("testSimple11", "NC(Cl)(Br)C(=O)O", true),
        ("unterminatedRingOpening", "C1CC", false),
        ("doublePositiveCharge1", "[C++]", true),
        ("doublePositiveCharge2", "[C+2]", true),
        ("doubleNegativeCharge1", "[O--]", true),
        ("doubleNegativeCharge2", "[O-2]", true),
        ("noIsotopeSpecified", "[NH3]", true),
        ("isotopeSpecified", "[15NH3]", true),
        ("badlyFormedSMILE1", "H5", false),
        ("badlyFormedSMILE2", "CH4", false),
        ("badlyFormedSMILE3", "13C", false),
        ("badlyFormedSMILE4", "C=#C", false),
        ("badlyFormedSMILE5", "C#=C", false),
        ("badlyFormedSMILE6", "F//C=C/F", false),
        ("badlyFormedSMILE7", "F/C=C/\\F", false),
        ("badlyFormedSMILE8", "F[C@@](Cl)Br", false),
        ("ringClosureHandling1", "C=1CN1", true),
        ("ringClosureHandling2", "C1CN=1", true),
        ("ringClosureHandling3", "C#1CN=1", false),
        ("ringClosureHandling4", "C=1CN=1", true),
        ("ringSupportGreaterThan10", "C%10CC%10", true),
        ("hydrogenHandling1", "[OH3+]", true),
        ("hydrogenHandling2", "[CH3][CH2][OH]", true),
        ("hydrogenHandling3", "[SH2]", true),
        ("hydrogenHandling4", "[SH4]", true),
        ("hydrogenHandling5", "[SH6]", true),
        ("hydrogenHandling6", "[SH3]", true),
        ("hydrogenHandling7", "[SH3+]", true),
        ("hydrogenHandling8", "[SH+]", true),
        ("hydrogenHandling9", "[SH3-]", true),
        ("hydrogenHandling10", "[SH-]", true),
        ("hydrogenHandling11", "[SH5+]", true),
        ("hydrogenHandling12", "[Li+]", true),
        ("hydrogenHandling13", "[NaH]", true),
        ("hydrogenHandling14", "-[SiH3]", true),
        ("hydrogenHandling15", "=[SiH2]", true),
        ("hydrogenHandling16", "#[SiH]", true),
        ("hydrogenHandling17", "[SiH3]-", true),
        ("hydrogenHandling18", "[SiH2]=", true),
        ("hydrogenHandling19", "[SiH]#", true),
        ("hydrogenHandling20", "=[Si]=", true),
        ("hydrogenHandling21", "[o+]1ccccc1", true),
        ("indicatedHydrogen", "Nc1[nH]c(=O)c2c(n1)nc[nH]2", true),
        ("chiralityTest1", "N[C@@H](F)C", true),
        ("chiralityTest2", "N[C@H](F)C", true),
        ("chiralityTest3", "C2.N1.F3.[C@@H]231", true),
        ("chiralityTest4", "[C@@H]231.C2.N1.F3", true),
        ("chiralityTest5", "[C@@H](Cl)1[C@H](C)(F).Br1", true),
        ("chiralityTest6", "I[C@@](Cl)(Br)F", true),
        ("chiralityTest7", "C[S@](N)=O", true),
        ("chiralityTest8", "[S@](C)(N)=O", true),
        ("testDoubleBondStereo1", "F/C=C/F", true),
        ("testDoubleBondStereo2", "F\\C=C/F", true),
        ("testDoubleBondStereo3", "C(/F)=C/F", true),
        ("testDoubleBondStereo4", "C(\\F)=C/F", true),
        ("testDoubleBondStereo5a", "CC1=C/F.O\\1", true),
        ("testDoubleBondStereo5b", "CC/1=C/F.O1", true),
        ("testDoubleBondStereo6", "CC1=C/F.O/1", true),
        ("testDoubleBondMultiStereo1", "F/C=C/C=C/C", true),
        ("testDoubleBondMultiStereo2", "F/C=C\\C=C/C", true),
        ("testDoubleBondMultiStereo3", "F/C=C\\C=C\\C", true),
        ("testDoubleBondMultiStereo4", "F/C=C\\C=CC", true),
        ("testDoubleBondNoela", "C/C=C\\1/NC1", true),
        ("testDoubleBondNoelb", "C/C=C1/NC1", true),
        ("testDoubleBondNoelc", "C/C=C\\1/NC/1", true),
        ("testDoubleBondNoeld", "C/C=C1/NC/1", true),
        ("testDoubleBondNoele", "C/C=C\\1\\NC1", false),
        ("testDoubleBondNoelf", "C/C=C\x01NC\x01", false),
        ("testDoubleBondNoelg", "C/C=C\x01/NC\x01", false),
        ("testDoubleBondCornerCase1", "C\\1NC1=C/C", true),
        ("testDoubleBondCornerCase2", "C1NC/1=C/C", true),
        ("testDoubleBondCornerCase3", "C/1=C/CCCCCC/1", false),
        ("testDoubleBondCornerCase4", "C\\1=C/CCCCCC\\1", false),
        ("testDoubleBondCornerCase5", "C\\1=C/CCCCCC/1", true),
        ("testDoubleBondCornerCase6", "C/1=C/CCCCCC\\1", true),
    ];
    for &(name, input, accepted) in fixtures {
        let mut graph = Graph::default();
        let result = build_fragment(&mut graph, input, "", "none");
        assert_eq!(result.is_ok(), accepted, "{name}: {input:?}: {result:?}");
    }
}
